const tabela2024 = [
    {
        nome: 'Fluminense',
        sigla: 'FLU',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Palmeiras',
        sigla: 'PAL',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Flamengo',
        sigla: 'FLA',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Corinthians',
        sigla: 'COR',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'São Paulo',
        sigla: 'SAO',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Santos',
        sigla: 'SAN',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Grêmio',
        sigla: 'GRE',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Internacional',
        sigla: 'INT',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Atlético Mineiro',
        sigla: 'CAM',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Cruzeiro',
        sigla: 'CRU',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Botafogo',
        sigla: 'BOT',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Vasco da Gama',
        sigla: 'VAS',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Athletico Paranaense',
        sigla: 'CAP',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Ceará',
        sigla: 'CEA',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Fortaleza',
        sigla: 'FOR',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Bahia',
        sigla: 'BAH',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: 'Goiás',
        sigla: 'GOI',
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    }
];

export default tabela2024;